### ISSUE TITLE
找不到串口设备

### ISSUE THREAD

**Issue by arthasby** [lcofjp/visual-serial#2]
按首页的步骤安装运行后，串口列表一栏提示"Not Found"。
单独下载serialport库，使用list函数是可以发现两个串口的。

运行环境：
* i5笔记本
* WIN7 64位
* USB串口线

**Comment by lcofjp** [comment]
第四部中编译成功了吗？
执行这个命令 ./node_modules/.bin/electron-rebuild
这个命令是编译serialport的，electron和node的本地模块不兼容，需要用electron-rebuild编译

**Comment by arthasby** [comment]
编译成功了，至少是这么提示的。
![issue](https://user-images.githubusercontent.com/3302021/32158539-2c05ee64-bd84-11e7-80f5-8458199849f8.png)

**Comment by lcofjp** [comment]
显示“Not Found”的主要原因应该就是serialport模块导入失败了，如果serialport导入成功，找不到设备的话，那一栏显示的是空。你可以试试下载我编译好的运行一下试试，如果能成功的话，可能还是编译过程出现问题。如果不是编译问题，那问题真就不好说了。

**Comment by arthasby** [comment]
解决了。
出错是因为加载`serialport.node`失败，因为没有找到此文件。
解决方法是：根据electron和serialnode的版本，[下载](https://github.com/node-serialport/node-serialport/releases/tag/v6.0.4)预编译好的`serialport.node`文件，放到`node_modules/serialport/build/Release`目录下。
